In [10]:
# imports

import numpy as np


def summary(a: np.ndarray) -> tuple[float, float, float, float]:
    """
    function that returns the minimum, maximum, mean and standard deviation of an array
    :param a: ndarray
    :return: tuple of float
       a tuple of four float values: min, max, mean, std
    Examples
    --------
    >>> summary(np.array([[1,2,3], [4,5,6]]))   # array sin nan
    (1, 6, 3.5, 1.707825127659933)
    >>> summary(np.array([[1,np.nan,3], [4,5,6]]))   # array con un nan
    (nan, nan, nan, nan)
    >>> summary(np.array([]))   # array vacío
    Traceback (most recent call last):
    ...
    ValueError: zero-size array to reduction operation minimum which has no identity
    """

    # write your code here
    if len(a) == 0:
        raise ValueError("zero-size array to reduction operation minimum which has no identity")

    return np.min(a), np.max(a), np.mean(a), np.std(a)


def check_nulls(a: np.ndarray) -> bool:
    """
    function that checks the validity od sensor data
    :param a: np.ndarray
    :return: bool
       indicates if data contains nan
    Examples
    --------
    >>> check_nulls(np.array([[1,2,3], [4,5,6]]))   # array sin nan
    True
    >>> check_nulls(np.array([[1,np.nan,3], [4,5,6]]))   # array con un nan
    False
    >>> check_nulls(np.array([]))   # array vacío
    True
    """
    # write your code here
    return not np.any(np.isnan(a))


def ith(temperature: np.ndarray, humidity: np.ndarray) -> np.ndarray:
    """
    Calculates the temperature-humidity index (THI) of each of the grid cells.
    The ith-value of each cell must be rounded to the nearest integer
    :param temperature:  np.ndarray
        temperatures collected by the sensor in a grid
    :param humidity:  np.ndarray
        humidity data collected by the sensor on a grid
    :return:  np.ndarray
        temperature-humidity index (THI) (round to the nearest integer)
    :raise ValueError: if shape of input arrays is not the same
    >>> ith(np.array([[1,2,3], [4,5,6]]), np.array([[1,2,3], [4,5,6]]))
    array([[47., 48., 48.],
           [49., 50., 51.]])
    >>> ith(np.array([[1,np.nan,3], [4,5,6]]), np.array([[1,2,3], [4,5,6]]))
    array([[47., nan, 48.],
           [49., 50., 51.]])
    >>> ith(np.array([[1], [4]]), np.array([[1], [4]]))
    array([[47.],
           [49.]])
    >>> ith(np.array([[2,3], [4,5]]), np.array([[1,2,3], [4,5,6]]))  # dimensiones distintas
    Traceback (most recent call last):
        ...
    ValueError: Shape of data sensors must be the same. Temperature: (2, 2) != humidity: (2, 3)
    """
    # write your code here
    if temperature.shape != humidity.shape:
        raise ValueError(
            f"Shape of data sensors must be the same. Temperature: {temperature.shape} != humidity: {humidity.shape}")

    result = np.round(0.8 * temperature + humidity / 100 * (temperature - 14.3) + 46.4)
    return result


def isStress(ith: np.ndarray) -> np.ndarray:
    """
    Determines the grid points where serious stress occurs.
    :param ith: np.ndarray
       temperature-humidity index (THI)
    :return: np.ndarray
       True values indicate serious stress
    >>> isStress(np.array([[47.], [49.]]))
    array([[False],
           [False]])
    >>> isStress(np.array([[47., 79., 48.], [49.,50. ,81.]]))
    array([[False,  True, False],
           [False, False,  True]])
    >>> isStress(np.array([[80, np.nan, 48.], [49., 50., 88.]]))
    array([[ True, False, False],
           [False, False,  True]])
    """
    # write your code here
    return np.greater(ith, 78)


import doctest

def test_doc() -> None:
    """
    The following instructions are to execute the tests of same functions
    If any test is fail, we will receive the notice when executing
    :return: None
    """
    doctest.run_docstring_examples(check_nulls, globals(), verbose=True)  # vemos los resultados de los test
    doctest.run_docstring_examples(ith, globals(), verbose=True)  # vemos los resultados de los test
    doctest.run_docstring_examples(isStress, globals(), verbose=False)  # solo los resultados de los test que fallan
    doctest.run_docstring_examples(summary, globals(), verbose=False)  # solo los resultados de los test que fallan
    
    
test_doc()

Finding tests in NoName
Trying:
    check_nulls(np.array([[1,2,3], [4,5,6]]))   # array sin nan
Expecting:
    True
ok
Trying:
    check_nulls(np.array([[1,np.nan,3], [4,5,6]]))   # array con un nan
Expecting:
    False
ok
Trying:
    check_nulls(np.array([]))   # array vacío
Expecting:
    True
ok
Finding tests in NoName
Trying:
    ith(np.array([[1,2,3], [4,5,6]]), np.array([[1,2,3], [4,5,6]]))
Expecting:
    array([[47., 48., 48.],
           [49., 50., 51.]])
ok
Trying:
    ith(np.array([[1,np.nan,3], [4,5,6]]), np.array([[1,2,3], [4,5,6]]))
Expecting:
    array([[47., nan, 48.],
           [49., 50., 51.]])
ok
Trying:
    ith(np.array([[1], [4]]), np.array([[1], [4]]))
Expecting:
    array([[47.],
           [49.]])
ok
Trying:
    ith(np.array([[2,3], [4,5]]), np.array([[1,2,3], [4,5,6]]))  # dimensiones distintas
Expecting:
    Traceback (most recent call last):
        ...
    ValueError: Shape of data sensors must be the same. Temperature: (2, 2) != humidity: (2, 3)
ok


In [4]:
datos_humedad = np.loadtxt('./datos/humedad.txt')
datos_humedad

array([[66.2, 66.1, 66.5, ..., 83.9, 83.8, 83.8],
       [83.7, 83.3, 83.4, ..., 78. , 78. , 77.9],
       [77.9, 77.9, 77.8, ..., 41.2, 41.2, 40.7],
       ...,
       [87.1, 87.1, 87.2, ..., 71.4, 71.3, 71.2],
       [71.3, 71.2, 70.8, ..., 58. , 58.5, 58.8],
       [58.8, 58.7, 57.2, ..., 44.6, 44.6, 44.9]])

In [5]:
datos_temperatura = np.loadtxt('./datos/temperaturas.txt')
datos_temperatura

array([[16., 16., 15., ..., 18., 18., 18.],
       [18., 18., 18., ..., 22., 21., 21.],
       [22., 22., 22., ..., 19., 19., 19.],
       ...,
       [17., 17., 17., ..., 19., 19., 19.],
       [19., 19., 18., ..., 19., 19., 19.],
       [19., 20., 20., ..., 19., 19., 19.]])

In [7]:
datos_ith = ith(datos_temperatura, datos_humedad)
datos_ith

array([[60., 60., 59., ..., 64., 64., 64.],
       [64., 64., 64., ..., 70., 68., 68.],
       [70., 70., 70., ..., 64., 64., 64.],
       ...,
       [62., 62., 62., ..., 65., 65., 65.],
       [65., 65., 63., ..., 64., 64., 64.],
       [64., 66., 66., ..., 64., 64., 64.]])

In [8]:
isStress(datos_ith)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [9]:
datos_ith[isStress(datos_ith)]

array([79., 79., 79., 79., 79., 79., 79., 79., 79., 80., 80., 79., 79.,
       79., 79., 79., 79., 79., 81., 80., 79., 79., 79., 79., 79., 80.,
       79., 80., 80., 79., 79., 80., 80., 80., 80., 80., 80., 80., 80.,
       80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
       80., 80., 82., 82., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
       80., 80., 80., 80., 80., 80., 80., 80., 80., 82., 82., 80., 80.,
       81., 81., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
       80., 80., 80., 82., 82., 80., 80., 80., 80., 82., 82., 80., 80.,
       80., 82., 80., 80., 82., 82., 82., 82., 82., 82., 82., 82., 82.,
       82., 82., 82., 82., 82., 82., 80., 80., 80., 80., 80., 82., 82.,
       82., 82., 82., 82., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
       80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80., 80.,
       80., 80., 80., 79., 79., 80., 80., 80., 79., 79., 79., 79., 79.,
       80., 80., 79., 79., 80., 80., 80., 80., 80., 80., 80., 80